Create Table HospitalMeasures(	Provider_Number numeric(500) PRIMARY KEY,
				Hospital_Name VARCHAR(500),
				Address VARCHAR(500), 
				City VARCHAR(500),
			        State CHAR(2),
				ZIP_Code INT,
			        Country_Name VARCHAR(500),
				HBIPS_2_Measure_Description VARCHAR(500),
				HBIPS_2_Overall_Rate_Per_1000 VARCHAR(500),
				HBIPS_2_Overall_Num numeric(10) NOT NULL,
				HBIPS_2_Overall_Den numeric(10) NOT NULL,
				HBIPS_2_Overall_Footnote INT,
				HBIPS_3_Measure_Description VARCHAR(500),
				HBIPS_3_Overall_Rate_Per_1000 VARCHAR(500),
				HBIPS_3_Overall_Num numeric(10) NOT NULL,
				HBIPS_3_Overall_Den numeric(10) NOT NULL,
				HBIPS_3_Overall_Footnote INT,
				HBIPS_5_Measure_Description VARCHAR(500),
				HBIPS_5_Overall_percentage_of_Total numeric(5),
				HBIPS_5_Overall_Num numeric(10) NOT NULL,
				HBIPS_5_Overall_Den numeric(10) NOT NULL,
				HBIPS_5_Overall_Footnote INT,
				HBIPS_6_Measure_Description VARCHAR(500),
				HBIPS_6_Overall_percentage_of_Total numeric(5),
				HBIPS_6_Overall_Num numeric(10) NOT NULL,
				HBIPS_6_Overall_Den numeric(10) NOT NULL,
				HBIPS_6_Overall_Footnote INT,
				HBIPS_7_Measure_Description VARCHAR(500),
				HBIPS_7_Overall_percentage_of_Total numeric(5),
				HBIPS_7_Overall_Num numeric(10) NOT NULL,
				HBIPS_7_Overall_Den numeric(10) NOT NULL,		
				HBIPS_7_Overall_Footnote INT,
				SUB_1_Measure_Description VARCHAR(500),
				SUB_1_percentage numeric(5),
				SUB_1_Numerator numeric(10) NOT NULL,
				SUB_1_Denominator numeric(10) NOT NULL,
				SUB_1_Footnote INT,
				TOB_1_Measure_Description VARCHAR(500),
				TOB_1_percentage numeric(5),
				TOB_1_Numerator numeric(10) NOT NULL,
				TOB_1_Denominator numeric(10) NOT NULL,
				TOB_1_Footnote INT,
				TOB_2_2a_Measure_Desc VARCHAR(500),
				TOB_2_percentage numeric(5),
				TOB_2_Numerator numeric(10) NOT NULL,
				TOB_2_2a_Denominator numeric(10) NOT NULL,	
				TOB_2_Footnote INT,
				TOB_2a_percentage numeric(5),
				TOB_2a_Numerator numeric(10) NOT NULL,
				TOB_2_2a__Denominator numeric(10) NOT NULL,
				TOB_2a_Footnote INT,
				PEoC_Measure_Description VARCHAR(500),
				PEoC_Assessed_Response VARCHAR(500),
				PEoC_Assessed_Footnote INT,
				EHR_Use_Measure_Description VARCHAR(500),
				EHR_Use_Response VARCHAR(500),
				EHR_Use_Footnote INT,
				HIE_Measure_Description VARCHAR(500),
				HIE_Response VARCHAR(500),	
				HIE_Footnote INT,
				Start_Date date,
				End_Date date,
				FUH_Measure_Description VARCHAR(500),
				FUH_30_percentage numeric(5),	
				FUH_30_Numerator numeric(10) NOT NULL,
				FUH_30_Denominator numeric(10) NOT NULL,
				FUH_30_Footnote INT,
				FUH_7_percentage numeric(5),
				FUH_7_Numerator numeric(10) NOT NULL,
				FUH_7_Denominator numeric(10) NOT NULL,
				FUH_7_Footnote INT,
				FUH_Measure_Start_Date date,
				FUH_Measure_End_Date date,
				IMM_2_Measure_Description VARCHAR(500),	
				IMM_2_percentage numeric(5),
				IMM_2_Numerator numeric(10) NOT NULL,
				IMM_2_Denominator numeric(10) NOT NULL,
				IMM_2_Footnote INT,
				HCP_Measure_Description VARCHAR(500),
				HCP_percentage numeric(5),
				HCP_Numerator numeric(10) NOT NULL,	
				HCP_Denominator numeric(10) NOT NULL,
				HCP_Footnote INT,
				Flu_Season_Start_Date date,	
				Flu_Season_End_Date date);


\copy HospitalMeasures FROM 'C:/Users/Shruti Jadon/Desktop/DatabaseProject/CreateDatabase/HP.csv' DELIMITER ',' CSV	

Create Table StateMeasures(     State CHAR(2) PRIMARY KEY,
				S_HBIPS_2_Measure_Description VARCHAR(500),
				S_HBIPS_2_Overall_Rate_Per_1000 numeric(500),
				S_HBIPS_2_Overall_Num numeric(10) NOT NULL,
				S_HBIPS_2_Overall_Den numeric(10) NOT NULL,
				S_HBIPS_3_Measure_Description VARCHAR(500),
				S_HBIPS_3_Overall_Rate_Per_1000 numeric(500),
				S_HBIPS_3_Overall_Num numeric(10) NOT NULL,
				S_HBIPS_3_Overall_Den numeric(10) NOT NULL,
				S_HBIPS_5_Measure_Description VARCHAR(500),
				S_HBIPS_5_Overall_percentage_of_Total numeric(5),
				S_HBIPS_5_Overall_Num numeric(10) NOT NULL,
				S_HBIPS_5_Overall_Den numeric(10) NOT NULL,
				S_HBIPS_6_Measure_Description VARCHAR(500),
				S_HBIPS_6_Overall_percentage_of_Total numeric(5),
				S_HBIPS_6_Overall_Num numeric(10) NOT NULL,
				S_HBIPS_6_Overall_Den numeric(10) NOT NULL,
				S_HBIPS_7_Measure_Description VARCHAR(500),
				S_HBIPS_7_Overall_percentage_of_Total numeric(5),
				S_HBIPS_7_Overall_Num numeric(10) NOT NULL,
				S_HBIPS_7_Overall_Den numeric(10) NOT NULL,
				S_SUB_1_Measure_Description VARCHAR(500),
				S_SUB_1_percentage numeric(5),
				S_SUB_1_Numerator numeric(10) NOT NULL,
				S_SUB_1_Denominator numeric(10) NOT NULL,
				S_TOB_1_Measure_Description VARCHAR(500),
				S_TOB_1_percentage numeric(5),
				S_TOB_1_Numerator numeric(10) NOT NULL,
				S_TOB_1_Denominator numeric(10) NOT NULL,
				TOB_2_2a_Measure_Desc VARCHAR(500),
				S_TOB_2_percentage numeric(5),
				S_TOB_2_Numerator numeric(10) NOT NULL,
				S_TOB_2_2a_Denominator numeric(10) NOT NULL,	
				S_TOB_2a_percentage numeric(5),
				S_TOB_2a_Numerator numeric(10) NOT NULL,
				S_TOB_2_2a__Denominator numeric(10) NOT NULL,
				S_PEoC_Measure_Description VARCHAR(500),
				S_PEoC_Yes_Count INT,
				S_PEoC_No_Count INT,
				S_PEoC_Yes_percentage numeric(5),
				S_PEoC_No_percentage numeric(5),
				S_EHR_Use_Measure_Description VARCHAR(500),
				S_EHR_Paper_Count INT,
				S_EHR_Non_Certified_Count INT,
				S_EHR_Certified_Count INT,	
				S_EHR_Paper_percentage numeric(5),
				S_EHR_Non_Certified_percentage numeric(5),
				S_EHR_Certified_percentage numeric(5),
				S_HIE_Measure_Description VARCHAR(500),
				S_HIE_Yes_Count INT,
				S_HIE_No_Count INT,
				S_HIE_Yes_percent numeric(500),	
				S_HIE_No_percent numeric(500),
				Start_Date date,
				End_Date date,
				S_FUH_Measure_Description VARCHAR(500),
				S_FUH_30_percentage numeric(5),	
				S_FUH_30_Numerator numeric(10) NOT NULL,
				S_FUH_30_Denominator numeric(10) NOT NULL,
				S_FUH_7_percentage numeric(5),
				S_FUH_7_Numerator numeric(10) NOT NULL,
				S_FUH_7_Denominator numeric(10) NOT NULL,
				S_FUH_Measure_Start_Date date,
				S_FUH_Measure_End_Date date,
				S_IMM_2_Measure_Description VARCHAR(500),	
				S_IMM_2_percentage numeric(5),
				S_IMM_2_Numerator numeric(10) NOT NULL,
				S_IMM_2_Denominator numeric(10) NOT NULL,
				S_HCP_Measure_Description VARCHAR(500),
				S_HCP_percentage numeric(5),
				S_HCP_Numerator numeric(10) NOT NULL,	
				S_HCP_Denominator numeric(10) NOT NULL,
				S_Flu_Season_Start_Date date,	
				S_Flu_Season_End_Date date);

\copy StateMeasures FROM 'C:/Users/Shruti Jadon/Desktop/DatabaseProject/CreateDatabase/SP.csv' DELIMITER ',' CSV	
	